linters:
  enable:
    - deadcode
    - errcheck
    - goconst
    - gofmt
    - golint
    - gosec
    - govet
    - ineffassign
    - interfacer
    - lll
    - megacheck
    - misspell
    - nakedret
    - structcheck
    - unconvert
    - varcheck
  enable-all: false
linters-settings:
  lll:
    line-length: 125
run:
  skip-files:
    - schema.go
    - pulumiManifest.go
  timeout: 10m
